name: Gradle Release
on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      project:
        description: 'Project'
        required: true
        type: choice
        options:
          - xtextasciidocplugin.parent
jobs:
  build:
    runs-on: [farhan5248-runners]
    permissions:
      contents: write
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Set up Git
      run: |
        git config --local user.name "${{ vars.ACTIONS_BOT_NAME }}"
        git config --local user.email "${{ vars.ACTIONS_BOT_EMAIL }}"
    - name: Publish Release version
      working-directory: ./${{ inputs.project }}
      run: |
        git reset --hard HEAD
        git clean -fdx
        git pull
        gradle release
        git push
        git push --tags
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Publish SNAPSHOT version
      working-directory: ./${{ inputs.project }}
      run: |
        git clean -fdx
        gradle publish
      env:
        GITHUB_TOKEN: ${{ github.token }}
